### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by cristoferdomingues** [erkobridee/restful-bookmarks-jerseyspring#1]
Bom dia!

Primeiramente gostaria de agradecer pela disponibilização do projeto, e gostaria de fazer uma pergunta.

Criei um bean como Scope("session"), mas ele dá erro:

 "No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request."

poderia exemplificar algo do tipo?

**Comment by erkobridee** [comment]
Opa blz,

bom até onde me lembro, com relação ao Jersey (e a arquitetura REST), não existe representação de sessão, cada requisição é única... também ainda não fiz nenhum teste com relação a representação de sessão no lado do servidor, usando o Jersey para responder as requisições

**Comment by cristoferdomingues** [comment]
Certo, obrigado.
